### PR TITLE
[WIP] Sanft

### PR DESCRIPTION
**Pull request by Vilin97**
Added a benchmarking script for spatial SSAs using the model from Sanft, 2015.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
What would it take for this to get finished?

**Comment by Vilin97** [comment]
Benchmarking flattened SSAs seems to result in segfaults, unclear why. Also, the pdf does not seem to get built either. I don't know how to resolve either of those two issues.
@isaacsas , do you have any insight? We looked into this at the end of August but couldn't figure out back then.

**Comment by isaacsas** [comment]
I think pdfs aren't getting built anymore, so that issue should hopefully go away.

I need to run this locally and see if I can reproduce the crashes on the flattened systems, hopefully soon.

**Comment by ChrisRackauckas** [comment]
Rebase so it uses the latest build scripts.

**Comment by isaacsas** [comment]
Updating this in https://github.com/SciML/SciMLBenchmarks.jl/pull/408 so can close here.

**Pull request closed without merging**
