### PR TITLE
Improve linear BVP benchmarks

### PR DESCRIPTION
**Pull request by ErikQQY**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@avik-pal do you know what's going on here?

**Comment by ErikQQY** [comment]
The CI is weird here, I can generate working precision diagrams locally, but the CI always complains about wrong usage of DiffEqDevTools.jl

**Comment by ChrisRackauckas** [comment]
you're instantiating the same manifest locally?

**Comment by ErikQQY** [comment]
Benchmarks for linear BVPs are all good now! ```MIRK``` method still beat ```Shooting```, ```MultipleShooting``` and ```BVPM2```🎉

**Pull request merged**
