### PR TITLE
Create lpnorm.jmd

### PR DESCRIPTION
**Pull request by Spinachboul**
Created the benchmark lpnorm.jl
Please look in this and suggest changes
@ChrisRackauckas  and @sathvikbhagavan

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
It looks like this was added to https://github.com/SciML/SciMLBenchmarks.jl/pull/919

**Comment by Spinachboul** [comment]
https://github.com/SciML/SciMLBenchmarks.jl/pull/919 is a PR for a different benchmark?

**Comment by Spinachboul** [comment]
I am currently adding new benchmarks to the Surrogates folder

**Comment by Spinachboul** [comment]
Oh ok

> It looks like this was added to #919

Oh fine then, can have reviews simultaneously for both the benchmarks

**Pull request closed without merging**
