### PR TITLE
Add ESDIRK methods benchmarks

### PR DESCRIPTION
**Pull request by ErikQQY**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
You'll need to also update the manifest.

**Comment by ErikQQY** [comment]
When I update the manifest, I encountered a compatibility issue, I tracked it down then I think maybe it is the ```SparsityDetection``` package restriction caused the error:

image

Since we already used Symbolics.jl, I think we can remove this package?

**Comment by ChrisRackauckas** [comment]
yes remove it

**Comment by ChrisRackauckas** [comment]
The new schemes may have some issue in their adaptivity or something. I'd isolate it down to smaller cases.

**Pull request closed without merging**
