### PR TITLE
Fix DynamicalODE Benchmarks

### PR DESCRIPTION
**Pull request by SebastianM-C**
Fix https://github.com/SciML/SciMLBenchmarks.jl/issues/261

The errors look like to be caused by some unicode issues.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Can you fix the manifest conflicts?

**Comment by SebastianM-C** [comment]
I kept the changes from my branch when resolving. I'll wait for the CI to see if it's ok. Sorry for the delay.

**Comment by SebastianM-C** [comment]
There seems to be some network issue with the CI :thinking:

**Comment by SebastianM-C** [comment]
Would it be ok to restart the tests?

**Comment by ChrisRackauckas** [comment]
I did

**Pull request merged**
