### PR TITLE
Update single_pendulums.jmd

### PR DESCRIPTION
**Pull request by Spinachboul**
Fixing the below issue 
https://github.com/SciML/SciMLBenchmarks.jl/issues/785
* The outputs are now not broken
* No significant changes in the code, just some minor fixes.

### The PR is ready to merge
@ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
That doesn't do anything about the loop?

**Comment by Spinachboul** [comment]
No, the loops were running fine

**Comment by ChrisRackauckas** [comment]
The plots are empty.

**Comment by Spinachboul** [comment]
The individual plots are working fine now

**Comment by Spinachboul** [comment]
Are the plots not working fine, or anything needs to be changed/fixed??
@ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
No plots are built, see the artifacts.

**Comment by Spinachboul** [comment]
Like the plots are not visible??

**Comment by ChrisRackauckas** [comment]
The artifacts showed the sol just errored.

**Comment by Spinachboul** [comment]
Oh ok, I'll fix it soon!

**Pull request closed without merging**
