### PR TITLE
Bayesian inference

### PR DESCRIPTION
**Pull request by ParamThakkar123**
## Checklist

- [X] Appropriate tests were added
- [X] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [X] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This PR is mixing changes.

**Comment by ChrisRackauckas** [comment]
Rebase so it runs the build

**Comment by ChrisRackauckas** [comment]
Oh wait shit, you didn't bump the manifest. The manifest needs to be bumped or it's not updating the actual packages used!

**Comment by ParamThakkar123** [comment]
> Oh wait shit, you didn't bump the manifest. The manifest needs to be bumped or it's not updating the actual packages used!

Oh, Okay. I will bump the manifest and make another pull request. I think I did it but maybe that didn't happen.

**Comment by ParamThakkar123** [comment]
Actually I was working on this one yesterday. But still some needed fix. I was working on it. Somehow all the checks passed but I noticed this yesterday that the manifest needs a bump

**Pull request merged**
