### PR TITLE
Add Gupta model benchmarks

### PR DESCRIPTION
**Pull request by TorkelE**
Add Gupta model benchmarks

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Unblocked.

The build result shows artifacts which has the text and plots

**Comment by TorkelE** [comment]
It seems to be blocked again. Is there some way for me to unblock it, or does it require someone with permission?

**Comment by ChrisRackauckas** [comment]
Great stuff, thanks. @utkarsh530 can you take a pass at these to add the extrapolation methods?

**Comment by utkarsh530** [comment]
Yeah, made #491

**Pull request merged**
