### PR TITLE
[WIP] A separate watcher for each file

### PR DESCRIPTION
**Pull request by ven-k**
- 2 test commits will follow to ensure it works

### CODE REVIEW

**Comment by ven-k** [comment]
@ChrisRackauckas, it watches and triggers pipeline for both files now.

**Comment by ChrisRackauckas** [comment]
Seems to be a real test failure?

**Comment by staticfloat** [comment]
So I think I fixed the error that Venkatesh was having; but there seems to be an actual test error here when running the package tests themselves.

**Comment by ChrisRackauckas** [comment]
https://github.com/JunoLab/Weave.jl/issues/422

**Pull request merged**
