### PR TITLE
Update bio benchmarks with comparisson

### PR DESCRIPTION
**Pull request by TorkelE**
This will add a final WP plot at the end of each of the Bio benchmarks files. 

The idea is that for the Catalyst paper, we can just download the figures from the SciMLBenchmakrs docs directly (since they only compare within Catalyst, unlike the main figure where we compare between tools). So I am basically adding proposed paper supplementary figures at the end here.

For each summary plot, I basically pick the best benchmarks across the docs. In some cases I also try and pick the best from each set (unless where a set only have really bad ones).

### CODE REVIEW

**Comment by TorkelE** [comment]
Seems a commit "`Merge pull request #4 from SciML/master`" snuck in. I think that was when I tried to ensure that my version of SciMLBecnhmarks (TorkelE/SciMLBenchmarks) was up-to-date with the main repo. Might this become a problem?

**Comment by TorkelE** [comment]
Before finalizing this I will need to figure out https://github.com/SciML/DiffEqDevTools.jl/issues/103 as well.
(I know that different markers are currently auto generated. But for clarity I have the same markers for the different solvers in the paper, so would be nice to use the same marker for e.g. `QNDF` in the other figures as in the WP diagrams)

**Comment by ChrisRackauckas** [comment]
> I think that was when I tried to ensure that my version of SciMLBecnhmarks (TorkelE/SciMLBenchmarks) was up-to-date with the main repo. Might this become a problem?

Yes, this is a problem. You're ignoring my code changes. Please rebase

**Comment by TorkelE** [comment]
Thanks, closing this while I try to figure out.

**Pull request closed without merging**
