### PR TITLE
Attempt another Bayesian inference build

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Tries to fix https://github.com/SciML/SciMLBenchmarks.jl/issues/484

### CODE REVIEW

**Comment by goedman** [comment]
Will take a look after next weekend (traveling abroad without my laptop).

**Comment by Vaibhavdixit02** [comment]
I think we'll wait for @goedman, no point in wasting more CI hours 😢

**Comment by ChrisRackauckas** [comment]
Thanks! Now we have something to start optimizing! We should change the Turing ODEs to use static arrays.

**Comment by storopoli** [comment]
Great! Thanks for the effort!

**Comment by Vaibhavdixit02** [comment]
Awesome! :tada:

**Pull request merged**
