### PR TITLE
Update the extrapolation benchmarks on new bio models

### PR DESCRIPTION
**Pull request by utkarsh530**
Things are now a bit better.
Multistate:
Screenshot 2022-09-08 180128
Multisite2:

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Are all of these small enough that a single BLAS thread is not gimping the non-parallel methods?

**Comment by utkarsh530** [comment]
The ones that I am testing are 9 ODEs and 66 ODEs.

**Comment by ChrisRackauckas** [comment]
okay that's fine. Those would be faster without BLAS threading. I'm curious though, don't the parallel methods just avoid BLAS entirely already?

**Comment by utkarsh530** [comment]
Yeah, they do. I just do it for comparison purposes for the non-parallel methods.

**Comment by utkarsh530** [comment]
Curious to know though what these Bio models are for.

**Comment by ChrisRackauckas** [comment]
It came up in https://www.biorxiv.org/content/10.1101/2022.07.30.502135v1

One of the benchmarks segfaulted?

**Comment by ChrisRackauckas** [comment]
This may get cut since it seems those benchmarks might be non-stiff.

**Comment by utkarsh530** [comment]
Yeah not sure about the segfault; this was the plot I got for multisite2.jmd:

image

**Comment by utkarsh530** [comment]
> This may get cut since it seems those benchmarks might be non-stiff.
Okay, I saw the PR for it too

**Comment by utkarsh530** [comment]
Just with benchmarking, it does seem non-stiff:

```
julia> @benchmark sol = solve(oprob,Vern9(),reltol = 1e-10,abstol=1e-10)
BenchmarkTools.Trial: 1755 samples with 1 evaluation.
 Range (min … max):  1.812 ms … 43.078 ms  ┊ GC (min … max): 0.00% … 85.37%
 Time  (median):     2.405 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   2.833 ms ±  2.622 ms  ┊ GC (mean ± σ):  7.46% ±  7.61%

           ▂▃▅█▅▃▁                                            
  ▆▅▆▆▆▄▃▃▅████████▆▅▅▅▄▄▃▃▃▃▃▄▃▃▄▄▄▄▄▄▃▄▃▃▄▄▄▄▄▃▃▄▃▃▃▃▃▁▂▁▂ ▄
  1.81 ms        Histogram: frequency by time        4.22 ms <

 Memory estimate: 1.59 MiB, allocs estimate: 2823.

julia> @benchmark sol = solve(oprob,ImplicitHairerWannerExtrapolation(min_order = 4, threading = OrdinaryDiffEq.PolyesterThreads()),reltol = 1e-10,abstol=1e-10)
BenchmarkTools.Trial: 595 samples with 1 evaluation.
 Range (min … max):  5.940 ms … 63.859 ms  ┊ GC (min … max): 0.00% … 43.17%
 Time  (median):     8.424 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   8.389 ms ±  3.400 ms  ┊ GC (mean ± σ):  1.05% ±  2.39%

    ▃▄▅            ▁  ▁  ▁▁▄▄▆█▆█▄▆▅▃▁ ▂                      
  ▅████▇▅▃▃▃▃▃▃▅▃▃▄██▇█▇▅███████████████▇█▅▆▄▅▃▄▃▃▁▂▁▃▃▂▂▂▁▃ ▄
  5.94 ms        Histogram: frequency by time        11.1 ms <

 Memory estimate: 1.10 MiB, allocs estimate: 10040.
```

**Pull request closed without merging**
