### PR TITLE
Manual S3 uploading

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
🎉 ... ?

**Comment by staticfloat** [comment]
Still cleaning it up, but yes, it's working.  :D

And to think, I only had to write three buildkite plugins.  :P

**Comment by staticfloat** [comment]
Alright, if this goes green, we can merge.  When we merge, it should automatically update the SciMLBenchmarksOutput repository.

**Comment by ChrisRackauckas** [comment]
Instant red, instant sadness.

**Comment by ChrisRackauckas** [comment]
🎉

**Pull request merged**
