### PR TITLE
bump Jumps to Catalyst v14, MTK v9

### PR DESCRIPTION
**Pull request by vyudu**
Trying to bump Jumps to new versions

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
The builder is currently on v1.10. Change the manifest to match.

**Comment by vyudu** [comment]
@ChrisRackauckas is this good to merge?

**Comment by ChrisRackauckas** [comment]
Mendes still has an issue?

# Plot solutions by each method
```julia
methods = (Direct(), FRM(), SortingDirect(), NRM(), DirectCR(), RSSA(), RSSACR(), Coevolve(), RDirect())
shortlabels = [string(leg)[15:end-2] for leg in methods]
tf      = 10.0 * jprob.tstop
prob    = DiscreteProblem(rn, jprob.u0, (0.0, tf), jprob.rates)
varlegs = ["A_P" "A_bound_P" "A_unbound_P" "RLA_P"]
@variables t S7(t) S8(t) S9(t)
varsyms = [
    [S7,S8,S9],
    [S9],
    [S7,S8],
    [S7]
]
varidxs = []
for vars in varsyms
    push!(varidxs, [findfirst(isequal(sym),rn.states) for sym in vars])
end
```

```
Error: ArgumentError: System ##ReactionSystem#260: variable states does not
 exist
```

**Comment by ChrisRackauckas** [comment]
I put a commit in that should handle that.

**Pull request merged**
