### PR TITLE
DynamicalODE Benchmark Updates

### PR DESCRIPTION
**Pull request by ParamThakkar123**
## Checklist

- [X] Appropriate tests were added
- [X] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [X] Any new documentation only uses public API

### CODE REVIEW

**Comment by ParamThakkar123** [comment]
@ChrisRackauckas The dynamicalODE benchmarks have been updated to the latest versions

**Comment by ParamThakkar123** [comment]
@ChrisRackauckas should I continue working on updating the other benchmarks too?? Under the small grants??

**Comment by ChrisRackauckas** [comment]
Sure though we are reworking the admin of the program since there were too many spam failures.

**Comment by ParamThakkar123** [comment]
> Sure though we are reworking the admin of the program since there were too many spam failures.

Okay. I am fine with it. Meanwhile, I will start fixing the other ones.

**Pull request merged**
