### PR TITLE
Make the LinearSolve default really fast

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
The benchmark machine is AMD EPYC so I'm not sure this makes sense?

**Comment by avik-pal** [comment]
Oh I did not know this is an AMD machine.

**Comment by avik-pal** [comment]
Though I was seeing a performance boost using MKLLUFactorization on my local machine which is AMD Ryzen 5

**Comment by ChrisRackauckas** [comment]
Ryzen is different from EPYC

**Comment by avik-pal** [comment]
MKLFactorization is outperforming Sundials https://julialang-buildkite-artifacts.s3.amazonaws.com/scimlbenchmarks/b8fc338f8e391fa2ae4ba1c70d88d2487946e5de1ead7b9b7b47cbf3b414be84/markdown/NonlinearProblem/chebyquad_function_wpd.svg in the few ones we were slower before

**Comment by ChrisRackauckas** [comment]
Interesting okay

**Comment by ChrisRackauckas** [comment]
Won't it do MKLLUFactorization by default?

**Comment by avik-pal** [comment]
No RFLU. But for very small problems < 12 x 12 linear systems it seems MKL is faster than RFLU. 

For tiny systems (like the 23 test problems), they converge in very few iterations so I had to override the auto selection and specify the linear solver.

**Comment by ChrisRackauckas** [comment]
That doesn't seem to match https://docs.sciml.ai/SciMLBenchmarksOutput/stable/LinearSolve/LUFactorization/ ?

**Comment by avik-pal** [comment]
I will rerun the LU Factorization benchmarks to confirm

**Comment by avik-pal** [comment]
with this version we outperform other solvers by quite a margin on the 23 test problems https://julialang-buildkite-artifacts.s3.amazonaws.com/scimlbenchmarks/6088a186f769fb6639c264cc9081088e88fc509c3a0badfa5e1fc8523bbe2e5c/markdown/NonlinearProblem/summary_wp_23test_problems.svg vs https://julialang-buildkite-artifacts.s3.amazonaws.com/scimlbenchmarks/40347df2fc990cc83af89b67507a10d179e55edf221fcdaa42ec0cf077c926bf/markdown/NonlinearProblem/summary_wp_23test_problems.svg

**Comment by avik-pal** [comment]
Ok RFLU is the fastest, we pretty much beat all other solvers now. https://julialang-buildkite-artifacts.s3.amazonaws.com/scimlbenchmarks/9f5966f371854f492c16af8970cbe7b351cd2ead6d551070c4d39144fe52e232/markdown/NonlinearProblem/summary_wp_23test_problems.svg

**Comment by ChrisRackauckas** [comment]
@amontoison have you looked into the Krylov performance issue?

**Comment by avik-pal** [comment]
> @amontoison have you looked into the Krylov performance issue?

Currently it only matters if the solve happens within a microsecond or so order. Not sure it is super relevant for real workloads

**Comment by ChrisRackauckas** [comment]
How come the LU choice is done then? Shouldn't the default choice just work then?

**Comment by avik-pal** [comment]
quite a few of those are in the 10^-5~10^-6 order, that's why I forced the selection. Let the latest ones run, then we should be able to compere better.

**Comment by avik-pal** [comment]
Okay there is some overhead https://julialang-buildkite-artifacts.s3.amazonaws.com/scimlbenchmarks/04e8c15a47530e484e74a62ae098b27b60a08706ce87c9ad1c8105cf92c9c3a6/markdown/NonlinearProblem/summary_wp_23test_problems.svg vs https://julialang-buildkite-artifacts.s3.amazonaws.com/scimlbenchmarks/9f5966f371854f492c16af8970cbe7b351cd2ead6d551070c4d39144fe52e232/markdown/NonlinearProblem/summary_wp_23test_problems.svg (See the order of solution time for the difference)

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaRegistries/General/pull/100661

**Comment by avik-pal** [comment]
## OLD

```julia
julia> for N in [2, 4, 6, 8, 12, 16]
           A = randn(N, N)
           b = randn(N)
           @info N
           @btime solve(LinearProblem($A, $b))
           @btime solve(LinearProblem($A, $b), LUFactorization())
           @btime solve(LinearProblem($A, $b), MKLLUFactorization())
           @btime solve(LinearProblem($A, $b), RFLUFactorization())
       end
[ Info: 2
  977.200 ns (46 allocations: 3.36 KiB)
  252.329 ns (5 allocations: 464 bytes)
  199.525 ns (5 allocations: 464 bytes)
  231.126 ns (6 allocations: 528 bytes)
[ Info: 4
  1.056 μs (46 allocations: 3.50 KiB)
  355.777 ns (5 allocations: 608 bytes)
  241.091 ns (5 allocations: 608 bytes)
  327.500 ns (6 allocations: 672 bytes)
[ Info: 6
  1.129 μs (46 allocations: 3.72 KiB)
  467.663 ns (5 allocations: 832 bytes)
  332.624 ns (5 allocations: 832 bytes)
  402.880 ns (6 allocations: 896 bytes)
[ Info: 8
  1.259 μs (46 allocations: 3.97 KiB)
  635.371 ns (5 allocations: 1.06 KiB)
  534.810 ns (5 allocations: 1.06 KiB)
  505.352 ns (6 allocations: 1.12 KiB)
[ Info: 12
  6.854 μs (46 allocations: 4.73 KiB)
  1.173 μs (5 allocations: 1.81 KiB)
  916.781 ns (5 allocations: 1.81 KiB)
  778.028 ns (6 allocations: 1.88 KiB)
[ Info: 16
  7.406 μs (46 allocations: 5.73 KiB)
  1.799 μs (5 allocations: 2.81 KiB)
  1.473 μs (5 allocations: 2.81 KiB)
  1.059 μs (6 allocations: 2.88 KiB)
```

## NEW

```julia
[ Info: 2
  450.330 ns (13 allocations: 1.11 KiB)
  257.202 ns (5 allocations: 464 bytes)
  198.656 ns (5 allocations: 464 bytes)
  240.987 ns (6 allocations: 528 bytes)
[ Info: 4
  511.948 ns (13 allocations: 1.25 KiB)
  344.634 ns (5 allocations: 608 bytes)
  235.002 ns (5 allocations: 608 bytes)
  314.936 ns (6 allocations: 672 bytes)
[ Info: 6
  615.638 ns (13 allocations: 1.47 KiB)
  474.653 ns (5 allocations: 832 bytes)
  346.403 ns (5 allocations: 832 bytes)
  420.538 ns (6 allocations: 896 bytes)
[ Info: 8
  703.563 ns (13 allocations: 1.72 KiB)
  612.546 ns (5 allocations: 1.06 KiB)
  479.282 ns (5 allocations: 1.06 KiB)
  483.723 ns (6 allocations: 1.12 KiB)
[ Info: 12
  6.238 μs (13 allocations: 2.48 KiB)
  1.149 μs (5 allocations: 1.81 KiB)
  872.061 ns (5 allocations: 1.81 KiB)
  773.537 ns (6 allocations: 1.88 KiB)
[ Info: 16
  6.727 μs (13 allocations: 3.48 KiB)
  1.801 μs (5 allocations: 2.81 KiB)
  1.501 μs (5 allocations: 2.81 KiB)
  1.083 μs (6 allocations: 2.88 KiB)
```

Still a minor overhead

**Comment by ChrisRackauckas** [comment]
Can you profile to find what it is?

**Comment by avik-pal** [comment]
image

**Comment by avik-pal** [comment]
we can avoid that check on non mac right?

**Comment by ChrisRackauckas** [comment]
Yes, or at least move it to `__init__`

**Comment by avik-pal** [comment]
```julia
# Without a Sys.isapple check
@benchmark solve($prob)
# BenchmarkTools.Trial: 10000 samples with 5 evaluations.
#  Range (min … max):  6.898 μs … 430.699 μs  ┊ GC (min … max): 0.00% … 86.91%
#  Time  (median):     7.193 μs               ┊ GC (median):    0.00%
#  Time  (mean ± σ):   7.688 μs ±   8.136 μs  ┊ GC (mean ± σ):  1.36% ±  1.50%

#     ▃█▅▁                                                       
#   ▁▄████▆▄▃▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▂
#   6.9 μs          Histogram: frequency by time        11.1 μs <

#  Memory estimate: 3.48 KiB, allocs estimate: 13.
@benchmark solve($prob, $RFLUFactorization())
# BenchmarkTools.Trial: 10000 samples with 10 evaluations.
#  Range (min … max):  1.245 μs … 182.954 μs  ┊ GC (min … max): 0.00% … 87.10%
#  Time  (median):     1.331 μs               ┊ GC (median):    0.00%
#  Time  (mean ± σ):   1.497 μs ±   4.092 μs  ┊ GC (mean ± σ):  5.82% ±  2.12%

#   ▁▅▇██▇▆▆▅▅▄▃▃▃▃▂▂▂▁▁▁                                       ▂
#   ███████████████████████▇▇▆▅▅▇▆▇▆▇▇██▇▇███▇█▇▆▆▇▇▅▅▆▅▅▆▅▆▆▅▄ █
#   1.24 μs      Histogram: log(frequency) by time      2.28 μs <

#  Memory estimate: 2.95 KiB, allocs estimate: 8.

# With a Sys.isapple check
@benchmark solve($prob)
# BenchmarkTools.Trial: 10000 samples with 10 evaluations.
#  Range (min … max):  1.365 μs … 218.619 μs  ┊ GC (min … max): 0.00% … 84.67%
#  Time  (median):     1.457 μs               ┊ GC (median):    0.00%
#  Time  (mean ± σ):   1.654 μs ±   5.024 μs  ┊ GC (mean ± σ):  7.15% ±  2.37%

#     ▃█▇▂                                                       
#   ▁▄████▇▆▄▃▃▃▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▂
#   1.37 μs         Histogram: frequency by time         2.5 μs <

#  Memory estimate: 3.48 KiB, allocs estimate: 13.
@benchmark solve($prob, $RFLUFactorization())
# BenchmarkTools.Trial: 10000 samples with 10 evaluations.
#  Range (min … max):  1.244 μs … 201.470 μs  ┊ GC (min … max): 0.00% … 87.02%
#  Time  (median):     1.312 μs               ┊ GC (median):    0.00%
#  Time  (mean ± σ):   1.460 μs ±   4.133 μs  ┊ GC (mean ± σ):  6.04% ±  2.13%

#   ▂▆██▇▆▆▄▄▃▂▁                                                ▂
#   █████████████▆▆▅▅▅▄▄▄▅▃▂▂▂▄▄▂▄▄▄▅▄▆▆▄▅▆▆▅▆▆▅▆▆▆▆▇▇▇▇▇▆▆▆▆▅▆ █
#   1.24 μs      Histogram: log(frequency) by time      2.27 μs <

#  Memory estimate: 2.95 KiB, allocs estimate: 8.
```

**Comment by ChrisRackauckas** [comment]
Okay so with that last PR the default handling is effectively done well enough to not influence benchmarks?

**Comment by avik-pal** [comment]
No there is still some overhead

**Comment by avik-pal** [comment]
But overhead is much lower now, see the battery problem. Our default alg is now faster than NLsolve https://julialang-buildkite-artifacts.s3.amazonaws.com/scimlbenchmarks/9ea497b129ab36019b607234f88ac41be36d27e88258fbf638e2542690d055b1/markdown/NonlinearProblem/battery_problem_work_precision.svg vs https://julialang-buildkite-artifacts.s3.amazonaws.com/scimlbenchmarks/ee3f2ec323d6b5d33dad1be91650ecc28b437387e525ccfb217eabefc1cc7992/markdown/NonlinearProblem/battery_problem_work_precision.svg

**Comment by avik-pal** [comment]
I feel for the small benchmarks we can hardcode the solver.

**Comment by ChrisRackauckas** [comment]
What overhead is left? We can probably just get that removed as well.

**Comment by avik-pal** [comment]
Is GenericLUFactorization actually faster for small systems? The resolution is bad https://docs.sciml.ai/SciMLBenchmarksOutput/stable/LinearSolve/figures/LUFactorization_1_1.png but seems like RFLU is still the faster there?

**Comment by ChrisRackauckas** [comment]
RFLU just calls GenericLUFactorization at that size.

**Comment by avik-pal** [comment]
```julia
julia> for N in [2, 4, 6, 8, 12, 16]
           A1, A2, A3, A4, A5 = [randn(N, N) for _ in 1:5]
           b = randn(N)
           @info N
           @btime solve_multiple_times($(copy(A1)), $(copy(A2)), $(copy(A3)),
               $(copy(A4)), $(copy(A5)), $(copy(b)), nothing)
           @btime solve_multiple_times($(copy(A1)), $(copy(A2)), $(copy(A3)), $(copy(A4)),
               $(copy(A5)), $(copy(b)), $LUFactorization())
           @btime solve_multiple_times($(copy(A1)), $(copy(A2)), $(copy(A3)), $(copy(A4)),
               $(copy(A5)), $(copy(b)), $MKLLUFactorization())
           @btime solve_multiple_times($(copy(A1)), $(copy(A2)), $(copy(A3)), $(copy(A4)),
               $(copy(A5)), $(copy(b)), $RFLUFactorization())
           @btime solve_multiple_times($(copy(A1)), $(copy(A2)), $(copy(A3)), $(copy(A4)),
               $(copy(A5)), $(copy(b)), $GenericLUFactorization())
       end
[ Info: 2
  1.249 μs (16 allocations: 1.23 KiB)
  1.286 μs (10 allocations: 832 bytes)
  887.524 ns (6 allocations: 512 bytes)
  1.097 μs (7 allocations: 576 bytes)
  951.870 ns (10 allocations: 832 bytes)
[ Info: 4
  2.706 μs (16 allocations: 1.44 KiB)
  3.083 μs (10 allocations: 1.02 KiB)
  2.238 μs (6 allocations: 656 bytes)
  2.083 μs (7 allocations: 720 bytes)
  2.392 μs (10 allocations: 1.02 KiB)
[ Info: 6
  7.154 μs (16 allocations: 1.72 KiB)
  7.725 μs (10 allocations: 1.30 KiB)
  6.803 μs (6 allocations: 880 bytes)
  3.945 μs (7 allocations: 944 bytes)
  6.838 μs (10 allocations: 1.30 KiB)
[ Info: 8
  21.551 μs (16 allocations: 2.03 KiB)
  20.944 μs (10 allocations: 1.61 KiB)
  14.552 μs (6 allocations: 1.11 KiB)
  8.329 μs (7 allocations: 1.17 KiB)
  21.245 μs (10 allocations: 1.61 KiB)
```

This is after removing a few more allocations in QR and NormalCholesky

**Comment by ChrisRackauckas** [comment]
Those already init with size zero arrays?

**Comment by avik-pal** [comment]
For the PivotedCase that still caused an overhead, so made it similar to the NoPivot case with a global precomputed value

**Comment by avik-pal** [comment]
```julia
[ Info: 2
  1.163 μs (12 allocations: 1.00 KiB)
  1.188 μs (10 allocations: 832 bytes)
  794.638 ns (6 allocations: 512 bytes)
  927.455 ns (7 allocations: 576 bytes)
  863.673 ns (10 allocations: 832 bytes)
[ Info: 4
  2.016 μs (12 allocations: 1.14 KiB)
  2.474 μs (10 allocations: 1.02 KiB)
  1.741 μs (6 allocations: 656 bytes)
  1.794 μs (7 allocations: 720 bytes)
  1.936 μs (10 allocations: 1.02 KiB)
[ Info: 6
  4.563 μs (12 allocations: 1.36 KiB)
  8.801 μs (10 allocations: 1.30 KiB)
  8.112 μs (6 allocations: 880 bytes)
  4.335 μs (7 allocations: 944 bytes)
  8.148 μs (10 allocations: 1.30 KiB)
[ Info: 8
  7.622 μs (12 allocations: 1.61 KiB)
  18.864 μs (10 allocations: 1.61 KiB)
  12.584 μs (6 allocations: 1.11 KiB)
  7.386 μs (7 allocations: 1.17 KiB)
  19.075 μs (10 allocations: 1.61 KiB)
[ Info: 12
  14.369 μs (12 allocations: 2.36 KiB)
  30.542 μs (10 allocations: 2.48 KiB)
  19.895 μs (6 allocations: 1.86 KiB)
  14.145 μs (7 allocations: 1.92 KiB)
  40.761 μs (10 allocations: 2.48 KiB)
[ Info: 16
  21.740 μs (12 allocations: 3.36 KiB)
  46.597 μs (10 allocations: 3.61 KiB)
  26.477 μs (6 allocations: 2.86 KiB)
  21.426 μs (7 allocations: 2.92 KiB)
  73.436 μs (10 allocations: 3.61 KiB)
```

with RFLU as the default even for small sizes

**Comment by avik-pal** [comment]
Little bit better but still not there yet

**Comment by avik-pal** [comment]
14% of the time (which accounts for the excess time in not specifying a default) is spent here 
image

**Comment by ChrisRackauckas** [comment]
How? It's just a struct 😅

**Comment by avik-pal** [comment]
I am as surprised as you are :sweat:

**Comment by avik-pal** [comment]
Not even sure where it is hitting that enum Symbol dispatch in Enum, that should be generated out

**Comment by avik-pal** [comment]
The location was incorrect because it is generated function, it was coming from the `Symbol(alg.alg)` which gets generated just above the line

**Comment by avik-pal** [comment]
Should be good to go once this build completes.

**Comment by ChrisRackauckas** [comment]
This took a turn but I think it was a major win for the average user.

**Pull request merged**
