### PR TITLE
full specialize in Bidkhori2012

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@utkarsh530 watch this one. If it fails we need to figure out what regressed.

**Comment by ChrisRackauckas** [comment]
Yeah something happened with an implicit extrapolation thing. @utkarsh530 would be good to fix it, I assume it has a quick fix.

**Comment by utkarsh530** [comment]
I think the error was before as well (Sparse Jacobian)? The automatic and analytic jacobian passed the tests, though, as usual.
https://benchmarks.sciml.ai/stable/Bio/Bidkhori2012/

**Comment by ChrisRackauckas** [comment]
oh it doesn't have sparse support? Okay, open an issue on OrdinaryDiffEq and we should cut it out of this benchmark.

**Pull request merged**
