### PR TITLE
Update BCR benchmark to Catalyst and MT

### PR DESCRIPTION
**Pull request by isaacsas**
I had to move the BCR benchmark to a new project environment (and hence made a new folder) as I wasn't able to get the Project.toml updated to use Catalyst (I was encountering dependency misery, with incompatible errors that I couldn't decipher). I suspect the errors were related to the geometric integrators package, perhaps due to it restricting the available polynomials.jl versions.

~~I haven't managed to run the benchmark to completion locally yet; just building the sparse and dense Jacobians with MT takes on the order of 30-60 minutes each. Hopefully it can go through on the server ok.~~

### CODE REVIEW

**Comment by isaacsas** [comment]
FWIW I let the generated script from the benchmark Weave file run overnight and got the following timings (this may not include compilation time for everything as some commands had previously run I think). This seems to work ok, so assuming everything will be re-run / generated on the benchmark server this should be ok to merge.
```julia
 ────────────────────────────────────────────────────────────────────────────
                                     Time                   Allocations      
                             ──────────────────────   ───────────────────────
      Tot / % measured:           6111s / 98.7%           2214GiB / 100%     

 Section             ncalls     time   %tot     avg     alloc   %tot      avg
 ────────────────────────────────────────────────────────────────────────────
 ODEProb DenseJac         1    3572s  59.2%   3572s   1246GiB  56.4%  1246GiB
 ODEProb SparseJac        1    2264s  37.6%   2264s    941GiB  42.6%   941GiB
 SparseJac Eval1          1    58.1s  0.96%   58.1s   3.61GiB  0.16%  3.61GiB
 DenseJac Eval1           1    58.1s  0.96%   58.1s   3.61GiB  0.16%  3.61GiB
 ODERHS Eval1             1    39.5s  0.66%   39.5s   3.52GiB  0.16%  3.52GiB
 ODEProb No Jac           1    33.9s  0.56%   33.9s   9.78GiB  0.44%  9.78GiB
 Parse Network            1    3.17s  0.05%   3.17s    436MiB  0.02%   436MiB
 Create ODESys            1    323ms  0.01%   323ms   44.6MiB  0.00%  44.6MiB
 DenseJac Eval2           1    888μs  0.00%   888μs      224B  0.00%     224B
 SparseJac Eval2          1    805μs  0.00%   805μs      256B  0.00%     256B
 ODERHS Eval2             1   88.3μs  0.00%  88.3μs      192B  0.00%     192B
 ────────────────────────────────────────────────────────────────────────────
```

**Comment by isaacsas** [comment]
Sparse convergence plot:
sparse–conv

**Comment by isaacsas** [comment]
@shashi This is probably the BCR script to use for testing going forward. Just activate the project.toml for the Bio folder and should be good to go.

**Comment by shashi** [comment]
Cool! Btw what's the link to the page with the results, the one in the README is now broken.

**Comment by isaacsas** [comment]
The benchmark needs to be run on the benchmarking server to generate the new html page and such. Then I’ll update the readme with the new link.

**Pull request merged**
