### PR TITLE
Transistor amplifier benchmark

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Added the MTK version of [transistor amplifier problem](https://archimede.uniba.it/~testset/problems/transamp.php), from #359

I'm not sure how the solvers are set up, so everything below line 58 (`tspan = (0.0, 0.2)`) is from ChemicalAkzoNobel.jmd

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Copy/pasting the solvers is 👍. They should all have about the same setup, though they can be tweaked a little bit to avoid any instabilities that can show up (which messes up the plot), so a tolerance may be tweaked down or specific solvers can be commented out / moved to a separate plot to accommodate that. We'll see what this generates.

**Comment by AayushSabharwal** [comment]
Weird. I'll try running this locally tomorrow and see if I can find the problem.

**Comment by AayushSabharwal** [comment]
Line 56 seems to be the issue, it can't create the system

**Comment by ChrisRackauckas** [comment]
@YingboMa does MTK support parsing linear mass matrices like that right now?

**Comment by YingboMa** [comment]
MTK tries to transform the system so that it is an almost identity matrix, i.e. the semi-explicit form. I tried it on the latest MTK, but initialization of the DAE then fails.

**Pull request closed without merging**
