### PR TITLE
Bump NeuralPDE v5 benchmarks

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by KirillZubov** [comment]
@ChrisRackauckas could you please check.

**Comment by ChrisRackauckas** [comment]
It looks like the two that built look good!

**Comment by KirillZubov** [comment]
why only two were built?

**Comment by ChrisRackauckas** [comment]
I'm not sure, maybe it just hit a compute limit. Let's merge and see. All 5 of the error ones worked, but only 2 of the optimization ones.

**Pull request merged**
