### PR TITLE
Parameter estimation

### PR DESCRIPTION
**Pull request by ParamThakkar123**
## Checklist

- [X] Appropriate tests were added
- [X] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [X] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I'm pretty sure this one needs updates to the callback syntax? Are you running these and making sure they are working? You keep telling me to review PRs that are not actually done and it's a big waste of time.

**Comment by ParamThakkar123** [comment]
If the error says something I have already dealt with then I try to solve it by myself. If there's something I am finding hard to figure , I ask you to review because I know you can help me out. Nothing else

**Comment by ParamThakkar123** [comment]
Sorry if this wasted your time and effort I can understand that. I will fix things so that everything runs well locally and I am able to run it locally so this doesn't happen again. Sorry again.

**Comment by ParamThakkar123** [comment]
My system is now able to handle Julia well. I can perform all the tests now

**Comment by ParamThakkar123** [comment]
How to deal with this one ?? Is it actually a bug here ??

**Comment by ChrisRackauckas** [comment]
I don't know, that would take some time to dive in, but I assume the majority of fixing this benchmark is likely figuring that one out.

**Comment by ChrisRackauckas** [comment]
This is mixing dynamical and parameter estimation.

Closing because this doesn't have any real changes in it.

@ParamThakkar123 I'm going to recommend this project as a SciML Small Grant for someone else since there has been no progress made on it.

**Pull request closed without merging**
