### PR TITLE
Add battery example to NonlinearProblem + Updates for NonlinearSolve v3

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by avik-pal** [comment]
@ChrisRackauckas what's up with the agents? Most of the recent builds seem stalled

**Comment by ChrisRackauckas** [comment]
It's just backed up

**Comment by ChrisRackauckas** [comment]
It ran, failed.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/Sundials.jl/pull/437

**Comment by avik-pal** [comment]
Oh no... It is due to the manifest being in 1.10 :disappointed:

**Comment by avik-pal** [comment]
@TorkelE do you know what is up with the PrettyTables error?

**Comment by TorkelE** [comment]
Not sure, cannot actually see the error

**Comment by avik-pal** [comment]
The battery example is running fine
image

**Comment by ChrisRackauckas** [comment]
We should really get subheaders in there.

**Comment by avik-pal** [comment]
I am confused by the segfault here https://buildkite.com/julialang/scimlbenchmarks-dot-jl/builds/1871#_

**Comment by ChrisRackauckas** [comment]
Retriggered and praying.

**Comment by avik-pal** [comment]
@ChrisRackauckas do `pdf`s not get uploaded as artifacts?

**Comment by ChrisRackauckas** [comment]
I think you'd need to modify https://github.com/SciML/SciMLBenchmarks.jl/blob/466a462799f64a9f0634dbb3ee26c42795afba7c/.buildkite/run_benchmark.yml#L35

**Comment by avik-pal** [comment]
image

Not sure how to get this done, but I want the script to upload all pdfs generated in the directory (cc maybe @staticfloat)

**Comment by ChrisRackauckas** [comment]
Why pdf and not something like SVG?

**Comment by avik-pal** [comment]
same problem right, the yml file needs to be updated. Either works for me. I want to have something that I can put in a paper, anything but jpg/pngs

**Comment by ChrisRackauckas** [comment]
Yeah just put svg right next to anything in the CI scripts that does .png and it should work.

**Comment by staticfloat** [comment]
I'm on vacation right now, but @thazhemadam can also help with this, he knows how.

**Comment by staticfloat** [comment]
@avik-pal do you want me to change the `.yml` to upload `.svg`s as well as `.pdf`s?

**Comment by avik-pal** [comment]
It worked :tada:. Though we need to look into Problem 6, that is the only one which none of the solvers, even non-julia ones can solve

**Pull request merged**
