### PR TITLE
Further fixes for MTK Benchmarks

### PR DESCRIPTION
**Pull request by chriselrod**
Some of the sizes were wrong.

### CODE REVIEW

**Comment by chriselrod** [comment]
thermalfluid_julia
thermalfluid_totaltime

**Comment by chriselrod** [comment]
thermalfluid_totaltime

**Comment by ChrisRackauckas** [comment]
That's a CI issue I pointed out to @thazhemadam . Just bump any bound in the Project.toml so that it's not file-specific but folder-specific and the CI is fixed. We should fix it but it's easy to work around.

**Comment by ChrisRackauckas** [comment]
ThermalFluid looks done

RCCircuit still has

```
Error: Number of elements not equal: 9 content elements and 8 labels.
```

**Pull request merged**
