### PR TITLE
MOL move to analytic errors for burgers

### PR DESCRIPTION
**Pull request by xtalax**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
No artifacts? Interesting.

**Comment by ChrisRackauckas** [comment]
It's building now, but throwing errors. Also printing a ton.

**Comment by ChrisRackauckas** [comment]
Oops merged, but that's fine. I need to setup the build system to handle a new folder. @xtalax address the errors ASAP though.

**Comment by xtalax** [comment]
@ChrisRackauckas This is still a .jl sketch, not a .jmd. Was having trouble passing analytic through MTK, the function is being generated correctly in MOL and passed to the ODEFunction method in MTK, but `prob.f.analytic` is still `nothing`

**Comment by xtalax** [comment]
oh I see that you moved to .jmd

**Pull request merged**
