### PR TITLE
Bump DiffEqParamEstim and update code

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This update drops all of the timings 😅. Can you add BenchmarkTools and an `@btime` on every solve?

**Comment by Vaibhavdixit02** [comment]
Oh :facepalm: yes I'll update that

**Comment by ChrisRackauckas** [comment]
You didn't add the `using BenchmarkTools`, and make sure it's in the Project/Manifest.

**Comment by Vaibhavdixit02** [comment]
>and make sure it's in the Project/Manifest.

Yes I checked it's there

**Pull request merged**
