### PR TITLE
Bump bio benchmarks

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@TorkelE I'm bumping to see performance, but can you help with the Catalyst 13 update on these?

**Comment by TorkelE** [comment]
Sounds goo.d Yes, Iäll have a look tomorrow morning.

**Comment by TorkelE** [comment]
Just checking, exactly what should I do? I could update the Catalyst version to the latest ones in the Project.toml files? Since the models are all loaded from .net files I don't think that should change anything.

Should I modify this PR directly? I think the last couple of times I've tried stuff like this in git things usually got messed up, but might be a good learning opportunity. Is there someone in the office that might be able to show the proper workflow for this?

**Comment by ChrisRackauckas** [comment]
Yeah just modify this PR.

**Comment by TorkelE** [comment]
I cannot make modifications to this PR directly (I think I'm not part of SciMLBenchmarks). I tried to make a PR to this PR: https://github.com/SciML/SciMLBenchmarks.jl/pull/622 Not sure if it worked out though

**Pull request merged**
